server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: devices-api
              uri: ${DEVICES_INTERNAL_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/devices/**
              filters:
                - StripPrefix=0

            - id: files-api
              uri: ${FILES_INTERNAL_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/files/**
              filters:
                - StripPrefix=0

            - id: subscription
              uri: ${SUBSCRIPTION_INTERNAL_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/subscriptions/**
              filters:
                - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_JWK_SET_URL:http://localhost:9000/oauth2/jwks}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
