server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_JWK_SET_URL:http://localhost:9000/oauth2/jwks}
