server:
  port: 8082

spring:
  mongodb:
    representation:
      uuid: STANDARD
    uri: ${MONGO_URI:mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/iotizze_db?authSource=admin}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_JWK_SET_URL:http://localhost:9000/oauth2/jwks}

base:
  url: ${AUTH_ISSUER_URL:http://localhost:9000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: swagger-ui
      use-pkce-with-authorization-code-grant: true
  api-docs:
    path: /api-docs
